Add admin users empty check
red-hat-data-services/odh-dashboard pull request #211
Opened 2022-04-26 14:54 UTC by DaoDaoNoCode

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] For commits that came from upstream, `[UPSTREAM]` has been prepended to the commit message
- [ ] JIRA link(s):
- [ ] The Jira story is acked
- [ ] An entry has been added to the latest build document in [Build Announcements Folder](https://drive.google.com/drive/folders/1sgkK1WZgGo9CXsLizNe0GbAzVKuSKrZL).
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious)
- [ ] The developer has manually tested the changes and verified that the changes work.

2022-04-26 15:07 UTC, lucferbux approved these changes
/lgtm

2022-08-05 18:05 UTC, dlabaj approved these changes

2022-08-05 18:07 UTC, dlabaj requested changes
Can we close this PR?

2022-08-23 13:32 UTC, mwaykole commented
hi, @DaoDaoNoCode  is this  PR  for when the admin user is not in admin groups then it will throw a warning?

2022-08-23 13:34 UTC, closed without merging