[rhoai-2.8] CVE-2024-43788 odh-dashboard-container: DOM Clobbering vulnerability in AutoPublicPathRuntimeModule
red-hat-data-services/odh-dashboard pull request #352
Opened 2024-09-11 15:23 UTC by DaoDaoNoCode

JIRA: [RHOAIENG-11991](https://issues.redhat.com/browse/RHOAIENG-11991)

Cherry-pick the commit https://github.com/opendatahub-io/odh-dashboard/pull/3185/commits/8f7c866ae0fe192f1d2a405187d8b61e3857de36 to fix the CVE in RHOAI 2.8.

2024-09-11 15:42 UTC, andrewballantyne commented on frontend/package-lock.json
Did you modify this directly? Seems npm install is modifying this lock file based on the failure...

2024-09-11 15:55 UTC, DaoDaoNoCode commented on frontend/package-lock.json
Yes, I cherry-picked the whole commit. I think I need to run `npm install` and push another commit to update the `package-lock.json` file.

2024-09-11 20:01 UTC, andrewballantyne approved these changes

2024-09-11 20:02 UTC, andrewballantyne requested changes
It occurs to me we don't actually have a 2.8.z ready to go 🤔 @dgutride do you know when the next release will be?

2024-09-12 11:33 UTC, dgutride commented
@andrewballantyne  - no, I am working on a more comprehensive approach to how we deal with issues like this.  In general, I'd rather we have fixes tagged and ready to go, but not moved into a branch until we know we are going to move forward with a change.  Staging things early might be problematic if they end up not wanting cve fixes for a z-stream for some reason.

2025-03-14 19:05 UTC, andrewballantyne commented
Out of date, if we need this we can come back for it. Still inside support window, no z-stream currently planned.

2025-03-14 19:05 UTC, closed without merging